spring.application.name=RecipeRecommendationBackend
server.port=8080

# configurable external API base URL
#mealdb.base-url=https://www.themealdb.com/api/json/v1/1
mealdb.base-url=http://localhost:9090

# actuator exposure
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# useful metric tags
management.metrics.tags.application=${spring.application.name}